### ISSUE TITLE
Indoor Campfires v2.1 ~ Wrong TLD Version

### ISSUE THREAD

**Issue by sbcopensource** [Xpazeman/tld-indoor-campfires#2]
Incorrect version on TLD Mod List main page TLD v2.17 
![Indoor Campfires v2 1](https://github.com/Xpazeman/tld-indoor-campfires/assets/80470918/64f48293-5bb0-486a-92d1-d92222161622)
Second page TLD v2.06 
![Indoor Campfires v2 1 #2](https://github.com/Xpazeman/tld-indoor-campfires/assets/80470918/584415b0-d697-44a4-8c53-7f799b4091bf)

**Comment by Xpazeman** [comment]
Not an error. First page shows that it has been tested in 2.17, second shows the latest patch note, which was updating it to work in 2.06 (which was the last time it broke)
